<!doctype html>

<head>
  <meta charset="utf-8">
  <title><?php echo($fileInfo['filename']) ?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta name="robots" content="noindex,nofollow">

  <link rel="apple-touch-icon" href="icon.png">
  <!-- Place favicon.ico in the root directory -->

  <link rel="stylesheet" href="../css/log.css">

</head>

<body>
  <header>
    <h1><?php echo($fileInfo['filename']) ?></h1>

    <h2>Overview</h2>
    <div class="summary">
      <h3>Summary</h3>
      <table>
        <tr>
          <td>Last 7 Days</td>
          <td>
            <?php echo $weekIndicators ?>
          </td>
        </tr>
        <tr>
          <td>Last 7 days</td>
          <td>
            <span class="passTag"><?php echo $last7pass; ?> passed</span>
            <span class="failTag"><?php echo $last7fail; ?> failed</span>
          </td>
        </tr>
        <tr>
          <td>Last 28 days</td>
          <td>
            <span class="passTag"><?php echo $last28pass; ?> passed</span>
            <span class="failTag"><?php echo $last28fail; ?> failed</span>
          </td>
        </tr>
        <tr>
          <td>This Month</td>
          <td>
            <span class="passTag"><?php echo $monthPass; ?> passed</span>
            <span class="failTag"><?php echo $monthFail; ?> failed</span>
          </td>
        </tr>
        <tr>
          <td>Last Month</td>
          <td>
            <span class="passTag"><?php echo $lastMonthPass; ?> passed</span>
            <span class="failTag"><?php echo $lastMonthFail; ?> failed</span>
          </td>
        </tr>
      </table>
    </div>

    <div class="sourcesGood">
      <h3>Passing Sources</h3>
      <table>
        <?php
        ksort($stats[$domainName]['pass']['sources']);
        foreach ($stats[$domainName]['pass']['sources'] as $domain => $ips) {
          sort($ips);
          $ips = implode('<br/>', $ips);
          echo "<tr><td>{$domain}</td><td>{$ips}</td></tr>\n";
        }
        ?>
      </table>
    </div>
    
    <div class="sourcesBad">
      <h3>Failing Sources</h3>
      <table>
        <?php
        ksort($stats[$domainName]['fail']['sources']);
        foreach ($stats[$domainName]['fail']['sources'] as $domain => $ips) {
          sort($ips);
          $ips = implode('<br/>', $ips);
          echo "<tr><td>{$domain}</td><td>{$ips}</td></tr>\n";
        }
        ?>
      </table>
    </div>    
  </header>

  <main>
    <h2>Report summaries</h2>
    <table>
      <colgroup>
        <col class="report">
        <col class="count">
        <col class="result">
        <col class="source">
      </colgroup>
      <thead>
        <th>Report</th>
        <th>Count</th>
        <th>Results</th>
        <th>Email Source</th>
      </thead>
      <?php
      // List all records grouped by date
      foreach( $records as $date => $dayRecords) {
        echo "<tbody data-content=\"{$date}\">\n";
        foreach($dayRecords as $time => $record) {
          echo "
            <tr {$record['statusClass']}>
            <td>{$record['report']}</td>
            <td>{$record['count']}</td>
            <td>{$record['result']}</td>
            <td>{$record['sources']}</td>
          </tr>\n";
        }
        echo "</tbody>\n";
      }
      ?>
    </table>
  </main>
  <footer>
    <p>Dashboard generated by DMARC-Buddy. Domains listed by most recently
      recieved DMARC report, grouped by day. Reports are typical sent with different delays
      by different reporting orgs (email service providers). For this reason
      all reports and records are shown grouped by date received.</p>
  </footer>
</body>

</html>